stages:
  - build
  - container
  - deploy

frontend_build:
  stage: build
  variables:
    CI: 'false'
  image: node:10-slim
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm i
    - npm run build
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - build/*

frontend_container:
  stage: container
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  image: docker:stable
  services:
  - docker:dind
  script: 
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} -f Dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  needs:
    - job: frontend_build
      artifacts: true
  when: on_success

frontend_deploy:
  stage: deploy
  image: bitnami/kubectl:1.17
  script:
    - kubectl -n ${CI_ENVIRONMENT_SLUG} set image deployment/${CI_PROJECT_NAME} ${CI_PROJECT_NAME}=${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
    - kubectl -n ${CI_ENVIRONMENT_SLUG} rollout restart deployment ${CI_PROJECT_NAME}
    - kubectl -n ${CI_ENVIRONMENT_SLUG} rollout status deployment ${CI_PROJECT_NAME}
  when: manual
  environment:
    name: homologacao
    url: https://app.prodf.verytecnologia.com.br
